repos:
-   repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
    - id: black
      pass_filenames: true
-   repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
    - id: flake8
      pass_filenames: true
      # this seems to need to be here in addition to setup.cfg
      exclude: vendored|__init__.py|examples
-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: 'v3.0.0a5'  # Use the sha / tag you want to point at
    hooks:
    - id: pylint
      exclude: notebooks|setup.py|tests/document01
      args:
        -  --disable=E0401,C0116,R0903
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: debug-statements
    - id: mixed-line-ending
-   repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
    - id: setup-cfg-fmt
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
    - id: pyupgrade
      args: ["--py36-plus"]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
    -   id: rst-backticks
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
        additional_dependencies:
            - toml
