parameters:
  package_install: 'NONE'
  job_name: ''

jobs:
- job: ${{ parameters.job_name }}
  strategy:
    matrix:
      Python36:
        pyver: 3.6
      Python37:
        pyver: 3.7
      Python38:
        pyver: 3.8
    maxParallel: 8
  timeoutInMinutes: 0
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - checkout: self
      submodules: true
    - script: |
        docker build --build-arg PACKAGES="${{parameters.package_install}}" \
          --build-arg PYVER=$(pyver) \
          --build-arg JOBNAME=${{parameters.job_name}} \
          -f .ci/Dockerfile .
