
name: Tests

on:
  push:
    branches-ignore:
      - 'release/**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    name: Run Test
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        name: Install Python 3.6
        with:
          python-version: '3.6'
      - uses: actions/setup-python@v1
        name: Install Python 3.6
        with:
          python-version: '3.7'
      - uses: actions/setup-python@v1
        name: Install Python 3.6
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: python -m pip install tox
      - name: RunTest
        run: python -m tox
